// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkj793dFEBLj1IKA7xFEIqdnSKJ5p8qIY',
    appId: '1:1092733022095:web:7b8ff1bc6da2415f1225fa',
    messagingSenderId: '1092733022095',
    projectId: 'housie-d854b',
    authDomain: 'housie-d854b.firebaseapp.com',
    storageBucket: 'housie-d854b.firebasestorage.app',
    measurementId: 'G-RM4P8DKMZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOxD1V2cZ1TZ2-jIC_tn56n-qKWDp8a1w',
    appId: '1:1092733022095:android:7aa2df67b318445f1225fa',
    messagingSenderId: '1092733022095',
    projectId: 'housie-d854b',
    storageBucket: 'housie-d854b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP1JatVe0XhD_JM-W6ffzfLTMUFA-8IkY',
    appId: '1:1092733022095:ios:dc6dd7841f1bea041225fa',
    messagingSenderId: '1092733022095',
    projectId: 'housie-d854b',
    storageBucket: 'housie-d854b.firebasestorage.app',
    androidClientId: '1092733022095-3m2n79bh742ttk2hq52fc5gk7bs447rv.apps.googleusercontent.com',
    iosClientId: '1092733022095-89d1kjp23btmb1jg9ev5eg2unikrh34t.apps.googleusercontent.com',
    iosBundleId: 'com.game.cardGame',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP1JatVe0XhD_JM-W6ffzfLTMUFA-8IkY',
    appId: '1:1092733022095:ios:dc6dd7841f1bea041225fa',
    messagingSenderId: '1092733022095',
    projectId: 'housie-d854b',
    storageBucket: 'housie-d854b.firebasestorage.app',
    androidClientId: '1092733022095-3m2n79bh742ttk2hq52fc5gk7bs447rv.apps.googleusercontent.com',
    iosClientId: '1092733022095-89d1kjp23btmb1jg9ev5eg2unikrh34t.apps.googleusercontent.com',
    iosBundleId: 'com.game.cardGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkj793dFEBLj1IKA7xFEIqdnSKJ5p8qIY',
    appId: '1:1092733022095:web:9db140406020a3ac1225fa',
    messagingSenderId: '1092733022095',
    projectId: 'housie-d854b',
    authDomain: 'housie-d854b.firebaseapp.com',
    storageBucket: 'housie-d854b.firebasestorage.app',
    measurementId: 'G-XWSYZYH6BK',
  );
}
