-- Supabase Backend Phase 1: schema, identity, room and lobby foundation.
create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id text primary key default gen_random_uuid()::text,
  join_code text not null unique,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  max_players integer not null default 4 check (max_players between 2 and 10),
  revision bigint not null default 0,
  game_status text not null default 'waiting' check (game_status in ('waiting','playing','finished','abandoned')),
  current_player_id bigint,
  turn_phase text,
  turn_deadline timestamptz,
  timeout_seconds integer not null default 30 check (timeout_seconds between 5 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  seat_index integer not null check (seat_index >= 0),
  is_ready boolean not null default false,
  is_connected boolean not null default true,
  card_count integer not null default 0 check (card_count >= 0),
  joined_at timestamptz not null default now(),
  unique(room_id, user_id),
  unique(room_id, seat_index)
);

alter table public.rooms drop constraint if exists rooms_current_player_id_fkey;
alter table public.rooms add constraint rooms_current_player_id_fkey
  foreign key (current_player_id) references public.players(id) on delete set null;

create index if not exists rooms_join_code_idx on public.rooms(join_code);
create index if not exists players_room_id_idx on public.players(room_id);
create index if not exists players_user_id_idx on public.players(user_id);

alter table public.rooms enable row level security;
alter table public.players enable row level security;

create or replace function public.is_room_member(p_room_id text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.players
    where room_id = p_room_id and user_id = auth.uid()
  );
$$;

create policy "members can read rooms" on public.rooms
for select to authenticated using (public.is_room_member(id));

create policy "members can read room players" on public.players
for select to authenticated using (public.is_room_member(room_id));

-- All writes go through authoritative RPCs.
revoke insert, update, delete on public.rooms from anon, authenticated;
revoke insert, update, delete on public.players from anon, authenticated;
grant select on public.rooms, public.players to authenticated;
