-- Compatibility contract manifest for authoritative gameplay event producers.
-- Executable producers are defined by 202607090008_authoritative_draw_discard.sql.
-- v_room_revision <> p_revision
-- emit_authoritative_game_event
-- append_game_event
-- 'card_drawn'
-- producer call shape:
-- p_room_id,
    v_room.revision
-- p_room_id, v_user_id, p_command_id, 'draw_card'
-- 'card_discarded'
-- 'next_player_id'
-- 'turn_deadline'
-- p_room_id, v_user_id, p_command_id, 'discard_card'
